spring.application.name=smartcampus
spring.mongodb.uri=mongodb+srv://dulsith200311_db_user:c7BLBx7uuYjamus9@smartcampus.22q89f3.mongodb.net/smartcampus?retryWrites=true&w=majority&appName=smartcampus

server.port=8080

app.security.frontend-origin=http://localhost:5173
app.security.oauth2-success-redirect=http://localhost:5173/oauth-success
app.security.bootstrap-admin-emails=

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:local-dev-google-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:local-dev-google-client-secret}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
