spring.application.name=smartcampus
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:}

server.port=8080

app.security.frontend-origins=http://localhost:5173,http://localhost:5174,http://192.168.56.1:5173,http://192.168.100.1:5173,http://192.168.252.1:5173,http://10.0.1.1:5173,http://172.28.27.229:5173
app.security.oauth2-success-redirect=http://localhost:5173/notifications
app.security.bootstrap-admin-emails=

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
